version: '3'
services:

  db: 
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - downloader

volumes: 
  pgdata:

networks:
  downloader:
    driver: bridge
